//! Combat tick + chase loop. Combat lives in two layers: `tick_combat`
//! is the per-tick top-of-loop call from `llm_driver` (chase, face,
//! attack); `chase_monster` is the pathfinding-driven approach loop that
//! polls monster position and re-routes when the target moves. Constants
//! at the top tune both the chase cadence and the attack-cooldown derived
//! from animation data.

use std::collections::HashMap;
use std::sync::Arc;
use std::time::{Duration, Instant};

use onlinerpg_shared::ClientMessage;
use tokio::sync::Mutex;
use tracing::{error, info, warn};

use crate::geom::PlanarDelta;
use crate::state::SharedState;

/// Minimum distance to a monster before attacking (matches client-side threshold).
const ATTACK_RANGE: f32 = 2.0;
/// Fallback attack cooldown if animation data is unavailable.
const DEFAULT_ATTACK_COOLDOWN_MS: u64 = 1500;
/// Path to animation durations JSON (generated by tools/extract-animation-durations.mjs).
/// Relative to agent-client working directory.
const ANIMATION_DURATIONS_PATH: &str = "data/animation_durations.json";

use super::movement::{MAX_STEP_DIST, MOVE_SPEED};

/// How often to poll when waiting (no active step to send), in ms.
const CHASE_IDLE_TICK_MS: u64 = 200;
/// Maximum chase duration before giving up (seconds).
const MAX_CHASE_SECS: f32 = 15.0;
/// Give up chasing monsters farther than this from the agent. Prevents NPC
/// guards from running far off their patrol to engage distant threats.
const MAX_CHASE_DISTANCE: f32 = 20.0;
/// How far the monster must move from our last target before we re-route.
const REROUTE_THRESHOLD: f32 = 1.5;

/// Load the attack (slash1) animation duration from the shared JSON file.
/// Returns the duration as milliseconds, or the default if loading fails.
pub(super) fn load_attack_cooldown() -> Duration {
    let Ok(text) = std::fs::read_to_string(ANIMATION_DURATIONS_PATH) else {
        warn!("Could not read {ANIMATION_DURATIONS_PATH}, using default attack cooldown");
        return Duration::from_millis(DEFAULT_ATTACK_COOLDOWN_MS);
    };

    // Structure: { "combat_melee": { "slash1": 1.533, ... }, ... }
    let Ok(data) = serde_json::from_str::<HashMap<String, HashMap<String, f64>>>(&text) else {
        warn!("Could not parse {ANIMATION_DURATIONS_PATH}, using default attack cooldown");
        return Duration::from_millis(DEFAULT_ATTACK_COOLDOWN_MS);
    };

    if let Some(duration_secs) = data.get("combat_melee").and_then(|m| m.get("slash1")) {
        let ms = (*duration_secs * 1000.0) as u64;
        info!("Loaded attack cooldown from animation data: {ms}ms");
        Duration::from_millis(ms)
    } else {
        warn!("slash1 animation not found in {ANIMATION_DURATIONS_PATH}, using default");
        Duration::from_millis(DEFAULT_ATTACK_COOLDOWN_MS)
    }
}

/// Execute one combat tick: check if target is alive and in range, chase or attack.
/// Returns Some(monster_id) to keep targeting, or None if combat ended.
pub(super) async fn tick_combat(
    state: &Arc<Mutex<SharedState>>,
    monster_id: String,
) -> Option<String> {
    // Chase until in range (handles monster movement during chase)
    match chase_monster(state, &monster_id).await {
        ChaseResult::InRange => {}
        ChaseResult::Lost | ChaseResult::Error => {
            info!("Combat ended: monster {monster_id} lost or error during chase");
            return None;
        }
    }

    // Face the monster before attacking (matches web client behavior)
    {
        let mut s = state.lock().await;
        if let Some(face_cmd) = s.face_monster_command(&monster_id) {
            if let Err(e) = s.send_command(face_cmd).await {
                error!("Failed to send face-monster move: {e}");
                return None;
            }
        }
    }

    // Send attack
    {
        let mut s = state.lock().await;
        let cmd = ClientMessage::PlayerAttack {
            monster_id: monster_id.clone(),
        };
        if let Err(e) = s.send_command(cmd).await {
            error!("Failed to send attack: {e}");
            return None;
        }
    }

    Some(monster_id)
}

pub(super) enum ChaseResult {
    InRange,
    Lost,
    Error,
}

/// Chase the monster until we're in attack range, using A* pathfinding.
/// Polls monster position every CHASE_TICK_MS and follows waypoints.
pub(super) async fn chase_monster(
    state: &Arc<Mutex<SharedState>>,
    monster_id: &str,
) -> ChaseResult {
    let chase_start = Instant::now();
    let mut path_waypoints: Vec<onlinerpg_shared::pathfinding::PathWaypoint> = Vec::new();
    let mut path_index = 0usize;
    let mut last_monster_x = 0.0f32;
    let mut last_monster_z = 0.0f32;

    loop {
        if chase_start.elapsed().as_secs_f32() > MAX_CHASE_SECS {
            warn!("Chase timeout for monster {monster_id}");
            return ChaseResult::Lost;
        }

        let (in_range, needs_repath, monster_pos) = {
            let s = state.lock().await;
            let monster_alive = s.nearby_monsters.contains_key(monster_id);
            let player_alive = s.self_player.as_ref().is_some_and(|p| p.health > 0);
            if !monster_alive || !player_alive {
                return ChaseResult::Lost;
            }

            let monster = &s.nearby_monsters[monster_id];
            let player = s.self_player.as_ref().unwrap();
            let to_monster = PlanarDelta::between(&player.position, &monster.position);
            let in_range = to_monster.dist <= ATTACK_RANGE;
            if to_monster.dist > MAX_CHASE_DISTANCE {
                info!(
                    "Giving up chase: monster {monster_id} is {:.1}m away (>{MAX_CHASE_DISTANCE}m)",
                    to_monster.dist
                );
                return ChaseResult::Lost;
            }

            let monster_shift = PlanarDelta::xz(
                last_monster_x,
                last_monster_z,
                monster.position.x,
                monster.position.z,
            )
            .dist;
            let needs_repath = path_waypoints.is_empty()
                || path_index >= path_waypoints.len()
                || monster_shift > REROUTE_THRESHOLD;

            (in_range, needs_repath, monster.position.clone())
        };

        if in_range {
            return ChaseResult::InRange;
        }

        if needs_repath {
            let result = {
                let s = state.lock().await;
                s.find_path_to(monster_pos.x, monster_pos.z, 0)
            };
            if result.waypoints.is_empty() {
                path_waypoints.clear();
            } else {
                path_waypoints = result.waypoints;
            }
            path_index = 0;
            last_monster_x = monster_pos.x;
            last_monster_z = monster_pos.z;
        }

        // Step toward next waypoint, subdividing long segments so the chase
        // walks at MOVE_SPEED. Fall back to a direct step toward the monster
        // if A* returned no path.
        let step_dist = if path_index < path_waypoints.len() {
            let wp = path_waypoints[path_index].clone();
            let mut s = state.lock().await;
            let player = match s.self_player.as_ref() {
                Some(p) => p,
                None => return ChaseResult::Lost,
            };
            let to_wp = PlanarDelta::to_xz(&player.position, wp.x, wp.z);

            if to_wp.dist < 0.1 {
                path_index += 1;
                0.0
            } else {
                let (step_x, step_z, sd) = if to_wp.dist <= MAX_STEP_DIST {
                    path_index += 1;
                    (wp.x, wp.z, to_wp.dist)
                } else {
                    let ratio = MAX_STEP_DIST / to_wp.dist;
                    (
                        player.position.x + to_wp.dx * ratio,
                        player.position.z + to_wp.dz * ratio,
                        MAX_STEP_DIST,
                    )
                };
                let cmd = ClientMessage::PlayerMove {
                    position: onlinerpg_shared::Position {
                        x: step_x,
                        y: player.position.y,
                        z: step_z,
                    },
                    rotation: to_wp.rotation(),
                    floor_level: wp.floor as i8,
                };
                s.self_floor_level = wp.floor;
                if let Err(e) = s.send_command(cmd).await {
                    error!("Failed to send chase move: {e}");
                    return ChaseResult::Error;
                }
                sd
            }
        } else {
            let mut s = state.lock().await;
            match compute_step_toward_monster(&s, monster_id) {
                Some((cmd, sd)) => {
                    if let Err(e) = s.send_command(cmd).await {
                        error!("Failed to send chase move: {e}");
                        return ChaseResult::Error;
                    }
                    sd
                }
                None => 0.0,
            }
        };

        let travel_ms = if step_dist > 0.0 {
            ((step_dist / MOVE_SPEED) * 1000.0) as u64
        } else {
            CHASE_IDLE_TICK_MS
        };
        tokio::time::sleep(Duration::from_millis(travel_ms.max(50))).await;
    }
}

/// Return a single MAX_STEP_DIST-limited move toward the monster, plus the
/// step's distance for sleep timing. Used as the fall-through when A* can't
/// return a path (e.g. monster on un-pathable terrain) so combat can still
/// inch the player closer at walk speed.
fn compute_step_toward_monster(
    state: &SharedState,
    monster_id: &str,
) -> Option<(ClientMessage, f32)> {
    let monster = state.nearby_monsters.get(monster_id)?;
    let self_player = state.self_player.as_ref()?;

    let to_monster = PlanarDelta::between(&self_player.position, &monster.position);
    if to_monster.dist <= ATTACK_RANGE {
        return None;
    }

    let target_dist = to_monster.dist - ATTACK_RANGE + 0.5;
    let step_dist = target_dist.min(MAX_STEP_DIST);
    let ratio = step_dist / to_monster.dist;
    let cmd = ClientMessage::PlayerMove {
        position: onlinerpg_shared::Position {
            x: self_player.position.x + to_monster.dx * ratio,
            y: monster.position.y,
            z: self_player.position.z + to_monster.dz * ratio,
        },
        rotation: to_monster.rotation(),
        floor_level: 0,
    };
    Some((cmd, step_dist))
}
